= The three goals to achieve the Java persistence mastering

After more than 15 years of JPA existence, the rise of NoSQL storages, and the increasing popularity of microservices architecture, software engineers have been facing new challenges when defining reliable persistence layers. The persistence layer has on its shoulders the heaviest weight of responsibility when considering architectures that are - or should we say, should be - customer-centric and domain-driven, resilient and scalable, and finally, evolutionary. We can adopt persistence paradigms such as SQL and NoSQL when handling data or even rely on integration with external services. With a considerable amount of options or flavors (+200 possibilities!), how can we technically reflect the business need without coupling it with such technical decisions? Or how to have a loosely coupled application and the persistence engine? This presentation will discuss the new trends in the modern persistence model around enterprise architecture. After 25 years of Java, we must revisit our persistence strategies and get to know all the latest hot techs, such as framework categories, data patterns, good practices, and several tips that will allow you to leverage the best of database integration with Java - the dream of scalability can finally become a reality.
